services:
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "10001:10001"
    networks:
      - private_net


  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    ports:
      - "10002:10002"
    environment:
      - PORT=10002

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
      - "10003:10003"
    environment:
      - PORT=10003

  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    ports:
      - "10004:10004"
    environment:
      - PORT=10004

  api-gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "10000:10000"
    networks:
      - private_net

networks:
  private_net:
    driver: bridge