services:
  - name: api-gateway
    type: web
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    ports:
      - port: 10000

  - name: user-service
    type: web
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./user-service/Dockerfile
    ports:
      - port: 10001

