basePath: /
definitions:
  handlers.InputOrder:
    properties:
      product_ids:
        items:
          type: integer
        type: array
      status:
        type: string
      user_id:
        type: integer
    type: object
  handlers.InputPayment:
    properties:
      amount:
        type: number
      order_id:
        type: integer
      user_id:
        type: integer
    type: object
  handlers.InputProduct:
    properties:
      category:
        type: string
      description:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  handlers.InputUser:
    properties:
      address:
        type: string
      email:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  models.Order:
    properties:
      id:
        type: integer
      order_date:
        type: string
      product_ids:
        items:
          type: integer
        type: array
      status:
        type: string
      total_price:
        type: number
      user_id:
        type: integer
    type: object
  models.Payment:
    properties:
      amount:
        type: number
      id:
        type: integer
      order_id:
        type: integer
      payment_date:
        type: string
      payment_status:
        type: string
      user_id:
        type: integer
    type: object
  models.Product:
    properties:
      category:
        type: string
      date_added:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  models.User:
    properties:
      address:
        type: string
      email:
        type: string
      id:
        type: integer
      registration_date:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is online store service API
  title: Online Store Service API
paths:
  /api/orders:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
        "404":
          description: No orders found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      parameters:
      - description: Order object
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/handlers.InputOrder'
      produces:
      - application/json
      responses:
        "201":
          description: Order created
          schema:
            type: string
        "400":
          description: Missing required fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new order
      tags:
      - orders
  /api/orders/{id}:
    delete:
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Order deleted
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete order by ID
      tags:
      - orders
    get:
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Order'
        "404":
          description: Order not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get order by ID
      tags:
      - orders
    put:
      consumes:
      - application/json
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      - description: Order object
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/handlers.InputOrder'
      produces:
      - application/json
      responses:
        "200":
          description: Order updated
          schema:
            type: string
        "400":
          description: Missing required fields
          schema:
            type: string
        "404":
          description: Order not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update order by ID
      tags:
      - orders
  /api/orders/search:
    get:
      parameters:
      - description: User ID
        in: query
        name: user_id
        type: integer
      - description: Order status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
        "400":
          description: Missing required fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Search orders
      tags:
      - orders
  /api/payments:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Payment'
            type: array
        "404":
          description: No payments found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all payments
      tags:
      - payments
    post:
      consumes:
      - application/json
      parameters:
      - description: Payment object
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/handlers.InputPayment'
      produces:
      - application/json
      responses:
        "201":
          description: Payment created
          schema:
            type: string
        "400":
          description: Missing required fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new payment
      tags:
      - payments
  /api/payments/{id}:
    delete:
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Payment deleted
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete payment by ID
      tags:
      - payments
    get:
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Payment'
        "404":
          description: Payment not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get payment by ID
      tags:
      - payments
    put:
      consumes:
      - application/json
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: integer
      - description: Payment object
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/handlers.InputPayment'
      produces:
      - application/json
      responses:
        "200":
          description: Payment updated
          schema:
            type: string
        "400":
          description: Missing required fields
          schema:
            type: string
        "404":
          description: Payment not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update payment by ID
      tags:
      - payments
  /api/payments/search:
    get:
      parameters:
      - description: Order ID
        in: query
        name: order_id
        type: integer
      - description: User ID
        in: query
        name: user_id
        type: integer
      - description: Payment status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Payment'
            type: array
        "400":
          description: Missing required fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Search payments
      tags:
      - payments
  /api/products:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "404":
          description: No products found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      parameters:
      - description: Product object
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handlers.InputProduct'
      produces:
      - application/json
      responses:
        "201":
          description: Product created
          schema:
            type: string
        "400":
          description: Missing required fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new product
      tags:
      - products
  /api/products/{id}:
    delete:
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Product deleted
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete product by ID
      tags:
      - products
    get:
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "404":
          description: Product not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get product by ID
      tags:
      - products
    put:
      consumes:
      - application/json
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product object
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handlers.InputProduct'
      produces:
      - application/json
      responses:
        "200":
          description: Product updated
          schema:
            type: string
        "400":
          description: Missing required fields
          schema:
            type: string
        "404":
          description: Product not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update product by ID
      tags:
      - products
  /api/products/search:
    get:
      parameters:
      - description: Product name
        in: query
        name: name
        type: string
      - description: Product category
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "400":
          description: Missing required fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Search products
      tags:
      - products
  /api/users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "404":
          description: No users found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.InputUser'
      produces:
      - application/json
      responses:
        "201":
          description: User created
          schema:
            type: string
        "400":
          description: Missing required fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new user
      tags:
      - users
  /api/users/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: User deleted
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete user by ID
      tags:
      - users
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get user by ID
      tags:
      - users
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.InputUser'
      produces:
      - application/json
      responses:
        "200":
          description: User updated
          schema:
            type: string
        "400":
          description: Missing required fields
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update user by ID
      tags:
      - users
  /api/users/search:
    get:
      parameters:
      - description: User name
        in: query
        name: name
        type: string
      - description: User email
        in: query
        name: email
        type: string
      - description: User role
        in: query
        name: role
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Missing required fields
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Search user
      tags:
      - users
swagger: "2.0"
